### ISSUE TITLE
 Version 1.1.1 - cannot find module '@ricokahler/pool'

### ISSUE THREAD

**Issue by maximilianschmid** [ricokahler/pool#36]
Upgrade from version 1.0.0 to version 1.1.1 is obviously a breaking change. 

Version 1.1.1 on NodeJS 14.15.4 produces the error
` Cannot find module '@ricokahler/pool'"`

Please use 2.x as new version or revert breaking change. 

Unfortunately I could not find updated documentation which describes migration path or how to upgrade.

**Comment by ricokahler** [comment]
My apologies. This was not meant to be a breaking change. Let me check the build. I'll have something out right away.

**Comment by ricokahler** [comment]
Testing it in alpha first but will promote shortly

**Comment by ricokahler** [comment]
@maximilianschmid let me know if this fixes it for you.
